packages:
  - apps/website/*
  - packages/*
  - tools/*

catalogMode: prefer

catalog:
  '@types/node': ^24
  typescript: ^5
  vite: npm:@voidzero-dev/vite-plus-core@0.2.2
  vite-plus: 0.2.2
overrides:
  vite: 'catalog:'
  '@vue/compat': beta
  '@vue/compiler-core': beta
  '@vue/compiler-dom': beta
  '@vue/compiler-sfc': beta
  '@vue/compiler-ssr': beta
  '@vue/compiler-vapor': beta
  '@vue/reactivity': beta
  '@vue/runtime-core': beta
  '@vue/runtime-dom': beta
  '@vue/runtime-vapor': beta
  '@vue/server-renderer': beta
  '@vue/shared': beta
  vue: beta
peerDependencyRules:
  allowAny:
    - vite
    - vue
  allowedVersions:
    vite: '*'

minimumReleaseAge: 0

allowBuilds:
  vue-demi: true
